### ISSUE TITLE
大二下学期总结和感想 | 惬意的小时光

### ISSUE THREAD

**Issue by FearwareX** [FearwareX/xiaoshiguang123.github.io#1]
http://blog.abplan.top/2019/07/05/%E5%A4%A7%E4%BA%8C%E4%B8%8B%E5%AD%A6%E6%9C%9F%E6%80%BB%E7%BB%93%E5%92%8C%E6%84%9F%E6%83%B3/ 

 大二下学期小记和总结博客很久没有更新了。最近也是很忙，今天完成了所谓的学校“web开发大赛”，虽然只是小比赛，但是还是有很多感想！ 学习方面期末考试  期末考试呢截止今天下午已经出来了所有成绩，没有挂科！本学期的课程还是挺多的，复习压力很大。尤其是重修的离散数学，当年老师直接取消考试资格，一年后再战还是很不错的！   理论性的东西很多对于我来讲并不擅长，我一直比较喜欢实用的应用性的东西，相比于去学

**Comment by xiaoshiguang123** [comment]
测试评论
